name: Delete old workflow runs
on: [workflow_dispatch]
jobs:
  delete_runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0