name: Deploy to GitHub Pages
on: [workflow_dispatch]
jobs:
  deploy:
    environment: github-pages
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run build
      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v2
        with:
          path: './build'
      - uses: actions/deploy-pages@v2
